CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS chats (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       UUID NOT NULL DEFAULT gen_random_uuid(),
    booking_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted    BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uk_chats_booking UNIQUE (booking_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_chats_uuid ON chats(uuid);

ALTER TABLE chats
    ADD CONSTRAINT fk_chats_booking
        FOREIGN KEY (booking_id) REFERENCES bookings(id)
        ON DELETE CASCADE;

ALTER TABLE bookings
    ADD COLUMN IF NOT EXISTS chat_id BIGINT;

DO $$ BEGIN
    ALTER TABLE bookings
        ADD CONSTRAINT fk_bookings_chat
            FOREIGN KEY (chat_id) REFERENCES chats(id)
            ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_bookings_chat_id
    ON bookings(chat_id)
    WHERE chat_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS chat_participants (
    chat_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (chat_id, user_id),
    CONSTRAINT fk_chat_participants_chat
        FOREIGN KEY (chat_id) REFERENCES chats(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_chat_participants_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_chat_participants_user ON chat_participants(user_id);

CREATE TABLE IF NOT EXISTS messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       UUID NOT NULL DEFAULT gen_random_uuid(),
    chat_id    BIGINT NOT NULL,
    author_id  BIGINT NOT NULL,
    content    VARCHAR(4000),
    photo      VARCHAR(600),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted    BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_messages_chat
        FOREIGN KEY (chat_id) REFERENCES chats(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_messages_author
        FOREIGN KEY (author_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_messages_chat_author_participant
        FOREIGN KEY (chat_id, author_id) REFERENCES chat_participants(chat_id, user_id),
    CONSTRAINT chk_messages_content_or_photo CHECK (
        (content IS NOT NULL AND length(btrim(content)) > 0)
        OR
        (photo IS NOT NULL AND length(btrim(photo)) > 0)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_uuid ON messages(uuid);
CREATE INDEX IF NOT EXISTS idx_messages_chat_created ON messages(chat_id, created_at);
CREATE INDEX IF NOT EXISTS idx_messages_author ON messages(author_id);

CREATE TABLE IF NOT EXISTS message_seen_by (
    message_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    PRIMARY KEY (message_id, user_id),
    CONSTRAINT fk_message_seen_by_message
        FOREIGN KEY (message_id) REFERENCES messages(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_message_seen_by_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_message_seen_by_user ON message_seen_by(user_id);
